#!/usr/bin/env node

/**
 * Omnira UI — Interactive Setup CLI
 *
 * Usage:  npx omnira-ui init
 *         node cli/omnira-init.mjs
 *
 * Walks the user through project naming, accent color selection,
 * and theme mode — then generates omnira.config.ts and a CSS
 * overrides file ready to import.
 */

import * as readline from "node:readline";
import * as fs from "node:fs";
import * as path from "node:path";
import { COLOR_PRESETS, DEFAULT_COLOR, DEFAULT_THEME, THEME_MODES } from "./presets.mjs";

// ── Helpers ──────────────────────────────────────────────────────────

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const GREEN = "\x1b[32m";
const CYAN = "\x1b[36m";
const YELLOW = "\x1b[33m";
const MAGENTA = "\x1b[35m";
const WHITE = "\x1b[97m";

function colorize(hex) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `\x1b[38;2;${r};${g};${b}m`;
}

function log(msg = "") {
    process.stdout.write(msg + "\n");
}

function blank() {
    log();
}

// ── Readline prompt ──────────────────────────────────────────────────

function createPrompt() {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
    });

    function ask(question) {
        return new Promise((resolve) => {
            rl.question(question, (answer) => resolve(answer.trim()));
        });
    }

    function close() {
        rl.close();
    }

    return { ask, close };
}

// ── Color picker (interactive list) ─────────────────────────────────

async function pickColor(promptFn) {
    const keys = Object.keys(COLOR_PRESETS);

    blank();
    log(`${BOLD}${WHITE}  Available accent colors:${RESET}`);
    blank();

    keys.forEach((key, i) => {
        const preset = COLOR_PRESETS[key];
        const swatch = colorize(preset.hex);
        const isDefault = key === DEFAULT_COLOR;
        const suffix = isDefault ? ` ${DIM}(default)${RESET}` : "";
        const num = String(i + 1).padStart(2, " ");
        log(`    ${DIM}${num}.${RESET} ${swatch}●${RESET}  ${preset.label}${suffix}  ${DIM}${preset.hex}${RESET}`);
    });

    blank();
    const answer = await promptFn(`  ${CYAN}?${RESET} ${BOLD}Pick a color${RESET} ${DIM}(number or name, default: lime):${RESET} `);

    if (!answer) return DEFAULT_COLOR;

    // Match by number
    const num = parseInt(answer, 10);
    if (!isNaN(num) && num >= 1 && num <= keys.length) {
        return keys[num - 1];
    }

    // Match by name (case-insensitive)
    const lower = answer.toLowerCase();
    if (COLOR_PRESETS[lower]) return lower;

    // Fuzzy match
    const match = keys.find((k) => k.startsWith(lower) || COLOR_PRESETS[k].label.toLowerCase().startsWith(lower));
    if (match) return match;

    log(`  ${YELLOW}!${RESET} Unknown color "${answer}", using lime.`);
    return DEFAULT_COLOR;
}

// ── Theme mode picker ───────────────────────────────────────────────

async function pickTheme(promptFn) {
    blank();
    log(`${BOLD}${WHITE}  Theme modes:${RESET}`);
    blank();
    log(`    ${DIM} 1.${RESET} Dark-first  ${DIM}(default)${RESET}`);
    log(`    ${DIM} 2.${RESET} Light-first`);
    blank();

    const answer = await promptFn(`  ${CYAN}?${RESET} ${BOLD}Default theme mode${RESET} ${DIM}(1 or 2, default: 1):${RESET} `);

    if (!answer || answer === "1" || answer.toLowerCase().startsWith("dark")) return "dark-first";
    if (answer === "2" || answer.toLowerCase().startsWith("light")) return "light-first";

    log(`  ${YELLOW}!${RESET} Unknown option "${answer}", using dark-first.`);
    return DEFAULT_THEME;
}

// ── File generators ─────────────────────────────────────────────────

function generateConfig(projectName, colorKey, themeMode) {
    return `/**
 * Omnira UI Configuration
 * Generated by: npx omnira-ui init
 *
 * This file defines your project's Omnira UI settings.
 * Import the generated CSS overrides in your root layout.
 */

const omniraConfig = {
    project: "${projectName}",
    accent: "${colorKey}",
    theme: "${themeMode}",
};

export default omniraConfig;
`;
}

function generateCSS(colorKey, themeMode) {
    const preset = COLOR_PRESETS[colorKey];
    if (!preset) return "";

    // If lime (default), no overrides needed
    if (colorKey === "lime") {
        return `/**
 * Omnira UI — Theme Overrides
 * Generated by: npx omnira-ui init
 *
 * Accent: ${preset.label} (${preset.hex})
 * Theme:  ${themeMode}
 *
 * Using default Lime preset — no overrides needed.
 * Import this file after globals.css in your root layout.
 */
`;
    }

    let css = `/**
 * Omnira UI — Theme Overrides
 * Generated by: npx omnira-ui init
 *
 * Accent: ${preset.label} (${preset.hex})
 * Theme:  ${themeMode}
 *
 * Import this file after globals.css in your root layout:
 *   import "./omnira-overrides.css";
 */

`;

    // Dark overrides
    css += `[data-theme="dark"] {\n`;
    for (const [prop, value] of Object.entries(preset.dark)) {
        css += `    ${prop}: ${value};\n`;
    }
    css += `}\n\n`;

    // Light overrides
    css += `[data-theme="light"] {\n`;
    for (const [prop, value] of Object.entries(preset.light)) {
        css += `    ${prop}: ${value};\n`;
    }
    css += `}\n`;

    return css;
}

// ── Main ─────────────────────────────────────────────────────────────

async function main() {
    const { ask, close } = createPrompt();

    blank();
    log(`  ${BOLD}${GREEN}✦${RESET} ${BOLD}${WHITE}Omnira UI Setup${RESET}`);
    log(`  ${DIM}The premium glassmorphism design system${RESET}`);
    blank();

    // 1. Project name
    const projectName = (await ask(`  ${CYAN}?${RESET} ${BOLD}Project name${RESET} ${DIM}(default: my-app):${RESET} `)) || "my-app";

    // 2. Accent color
    const colorKey = await pickColor(ask);
    const preset = COLOR_PRESETS[colorKey];

    // 3. Theme mode
    const themeMode = await pickTheme(ask);

    close();

    // ── Summary ──
    blank();
    log(`  ${DIM}─────────────────────────────────────${RESET}`);
    blank();
    log(`  ${BOLD}${WHITE}Configuration:${RESET}`);
    blank();
    log(`    ${DIM}Project:${RESET}  ${WHITE}${projectName}${RESET}`);
    log(`    ${DIM}Accent:${RESET}   ${colorize(preset.hex)}●${RESET}  ${preset.label} ${DIM}(${preset.hex})${RESET}`);
    log(`    ${DIM}Theme:${RESET}    ${WHITE}${themeMode === "dark-first" ? "Dark-first" : "Light-first"}${RESET}`);
    blank();

    // ── Write files ──
    const cwd = process.cwd();
    const configPath = path.join(cwd, "omnira.config.ts");
    const cssPath = path.join(cwd, "omnira-overrides.css");

    // Config file
    fs.writeFileSync(configPath, generateConfig(projectName, colorKey, themeMode), "utf-8");
    log(`  ${GREEN}✓${RESET} Created ${BOLD}omnira.config.ts${RESET}`);

    // CSS overrides
    const cssContent = generateCSS(colorKey, themeMode);
    fs.writeFileSync(cssPath, cssContent, "utf-8");
    log(`  ${GREEN}✓${RESET} Created ${BOLD}omnira-overrides.css${RESET}`);

    blank();

    if (colorKey !== "lime") {
        log(`  ${DIM}Import the overrides in your root layout:${RESET}`);
        blank();
        log(`    ${MAGENTA}import${RESET} ${WHITE}"./globals.css"${RESET};`);
        log(`    ${MAGENTA}import${RESET} ${WHITE}"./omnira-overrides.css"${RESET};`);
        blank();
    }

    log(`  ${GREEN}✓${RESET} ${BOLD}${WHITE}Ready to go!${RESET} Run ${CYAN}npx omnira-ui${RESET} to reconfigure anytime.`);
    blank();
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
