"use client";

import { cn } from "@/lib/cn";
import { useConfigurator } from "@/lib/configurator-context";
import { ACCENT_PRESETS, FONT_PRESETS, RADIUS_PRESETS, GRAY_PRESETS } from "@/lib/configurator-presets";
import { copyToClipboard } from "@/lib/copy-to-clipboard";
import { Paintbucket, CloseCircle, Refresh2, Copy } from "iconsax-react";
import s from "./ConfiguratorPanel.module.css";

/* ══════════════════════════════════════════════
   Helpers
   ══════════════════════════════════════════════ */

function contrastText(hex: string): string {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    const lum = (0.299 * r + 0.587 * g + 0.114 * b) / 255;
    return lum > 0.5 ? "#000" : "#fff";
}

function generateConfigExport(state: { accent: string; font: string; radius: string; grayPalette: string }): string {
    const accentPreset = ACCENT_PRESETS[state.accent];
    const fontPreset = FONT_PRESETS[state.font];
    const radiusPreset = RADIUS_PRESETS[state.radius];
    const grayPreset = GRAY_PRESETS[state.grayPalette];

    const formatVars = (vars: Record<string, string>, indent: string) =>
        Object.entries(vars).map(([k, v]) => `${indent}${k}: ${v};`).join("\n");

    const fontImport = fontPreset?.googleUrl
        ? `@import url("${fontPreset.googleUrl}");\n\n`
        : "";

    const darkAccent = accentPreset ? formatVars(accentPreset.dark, "    ") : "";
    const darkGray = grayPreset ? formatVars(grayPreset.dark, "    ") : "";
    const lightAccent = accentPreset ? formatVars(accentPreset.light, "    ") : "";
    const lightGray = grayPreset ? formatVars(grayPreset.light, "    ") : "";
    const radiusVars = radiusPreset ? formatVars(radiusPreset.values, "    ") : "";
    const fontVars = fontPreset
        ? `    --font-body: ${fontPreset.body};\n    --font-display: ${fontPreset.display};`
        : "";

    return `/*
 * Omnira UI — Custom Theme
 * Generated by the Omnira UI Configurator
 *
 * Preset: ${accentPreset?.label || state.accent} accent, ${fontPreset?.label || state.font} font,
 *         ${radiusPreset?.label || state.radius} radius, ${grayPreset?.label || state.grayPalette} gray palette
 *
 * Usage: Paste this file into your project as "omnira-overrides.css"
 *        and import it AFTER your base globals.css:
 *
 *        @import "./globals.css";
 *        @import "./omnira-overrides.css";
 */

${fontImport}/* ── Dark theme overrides ── */
[data-theme="dark"] {
${darkAccent}
${darkGray}
${radiusVars}
${fontVars}
}

/* ── Light theme overrides ── */
[data-theme="light"] {
${lightAccent}
${lightGray}
${radiusVars}
${fontVars}
}`;
}

/* ══════════════════════════════════════════════
   Component
   ══════════════════════════════════════════════ */

export function ConfiguratorPanel() {
    const {
        accent, setAccent,
        font, setFont,
        radius, setRadius,
        grayPalette, setGrayPalette,
        reset,
        isOpen, togglePanel,
    } = useConfigurator();

    const handleCopy = () => {
        const code = generateConfigExport({ accent, font, radius, grayPalette });
        copyToClipboard(code);
    };

    return (
        <>
            {/* Floating toggle button */}
            <button
                className={cn(s.toggleBtn, isOpen && s.toggleBtnActive)}
                onClick={togglePanel}
                aria-label="Toggle theme configurator"
            >
                <Paintbucket size={20} variant="Bulk" color="currentColor" />
            </button>

            {/* Panel */}
            <aside className={cn(s.panel, isOpen && s.panelOpen)}>
                {/* Header */}
                <div className={s.header}>
                    <span className={s.headerTitle}>Customize</span>
                    <div className={s.headerActions}>
                        <button className={s.headerBtn} onClick={togglePanel} aria-label="Close panel">
                            <CloseCircle size={18} variant="Bulk" color="currentColor" />
                        </button>
                    </div>
                </div>

                {/* Body */}
                <div className={s.body}>
                    {/* ── Accent Color ── */}
                    <div className={s.section}>
                        <div className={s.sectionHeader}>
                            <span className={s.sectionLabel}>Accent Color</span>
                            <span className={s.sectionValue}>{ACCENT_PRESETS[accent]?.label}</span>
                        </div>
                        <div className={s.swatches}>
                            {Object.entries(ACCENT_PRESETS).map(([key, preset]) => (
                                <button
                                    key={key}
                                    className={cn(s.swatch, accent === key && s.swatchActive)}
                                    style={{ background: preset.hex }}
                                    onClick={() => setAccent(key)}
                                    aria-label={preset.label}
                                >
                                    {accent === key && (
                                        <span className={s.swatchCheck} style={{ color: contrastText(preset.hex) }}>
                                            ✓
                                        </span>
                                    )}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* ── Font ── */}
                    <div className={s.section}>
                        <div className={s.sectionHeader}>
                            <span className={s.sectionLabel}>Font</span>
                            <span className={s.sectionValue}>{FONT_PRESETS[font]?.label}</span>
                        </div>
                        <div className={s.fontList}>
                            {Object.entries(FONT_PRESETS).map(([key, preset]) => (
                                <button
                                    key={key}
                                    className={cn(s.fontItem, font === key && s.fontItemActive)}
                                    onClick={() => setFont(key)}
                                    style={{ fontFamily: preset.body }}
                                >
                                    {preset.label}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* ── Border Radius ── */}
                    <div className={s.section}>
                        <div className={s.sectionHeader}>
                            <span className={s.sectionLabel}>Border Radius</span>
                            <span className={s.sectionValue}>{RADIUS_PRESETS[radius]?.label}</span>
                        </div>
                        <div className={s.pills}>
                            {Object.entries(RADIUS_PRESETS).map(([key, preset]) => (
                                <button
                                    key={key}
                                    className={cn(s.pill, radius === key && s.pillActive)}
                                    onClick={() => setRadius(key)}
                                >
                                    {preset.label}
                                </button>
                            ))}
                        </div>
                        <div
                            className={s.radiusPreview}
                            style={{ borderRadius: RADIUS_PRESETS[radius]?.values["--radius-md"] || "14px" }}
                        />
                    </div>

                    {/* ── Gray Palette ── */}
                    <div className={s.section}>
                        <div className={s.sectionHeader}>
                            <span className={s.sectionLabel}>Gray Palette</span>
                            <span className={s.sectionValue}>{GRAY_PRESETS[grayPalette]?.label}</span>
                        </div>
                        <div className={s.pills}>
                            {Object.entries(GRAY_PRESETS).map(([key, preset]) => (
                                <button
                                    key={key}
                                    className={cn(s.pill, grayPalette === key && s.pillActive)}
                                    onClick={() => setGrayPalette(key)}
                                >
                                    {preset.label}
                                </button>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Footer */}
                <div className={s.footer}>
                    <button className={cn(s.footerBtn, s.resetBtn)} onClick={reset}>
                        <Refresh2 size={14} variant="Bulk" color="currentColor" style={{ marginRight: 4, verticalAlign: "middle" }} />
                        Reset
                    </button>
                    <button className={cn(s.footerBtn, s.copyBtn)} onClick={handleCopy}>
                        <Copy size={14} variant="Bulk" color="currentColor" style={{ marginRight: 4, verticalAlign: "middle" }} />
                        Copy Config
                    </button>
                </div>
            </aside>
        </>
    );
}
